[build]
  publish = "themes/public"
  command = "cd themes && hugo --gc --themesDir ../.."
  
[build.environment]
  HUGO_VERSION = "0.79.0"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "/"

[[plugins]]
package = "netlify-plugin-image-optim"

[[redirects.fr]]
  from = "https://www.lcdigitale.fr"
  to = "https://www.lcdigitale.fr/fr"
  conditions = {Language = ["fr"], Country = ["FR"], Role = ["admin"]}
  status = 301
  force = true

[[redirects.en]]
  from = "https://www.lcdigitale.fr"
  to = "https://www.lcdigitale.fr/en"
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}
  status = 301
  force = true
