[build]
  publish = "themes/exampleSite/public"
  command = "cd themes/exampleSite/public && hugo --gc --themesDir ../../.."
  
[build.environment]
  HUGO_VERSION = "0.79.0"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "/"