################################# Default configuration ###################
baseURL = "https://www.lcdigitale.fr"
title = "LCDIGITALE- Développeur Web Indépendant - création de sites web"
defaultContentLanguage = "fr"
# defaultContentLanguageInSubdir = "true"
languageCode = "fr-fr"
themes = "meghna-hugo"
themesDir = "../.."
# post pagination
paginate = "6"
# post excerpt
summaryLength = "30"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = ["en"]
# Enable robots.txt generation
enableRobotsTXT = "true"

############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"


################### French Navigation ########################
[[Languages.fr.menu.main]]
name = "À propos"
pre = "#"
url = "about"
weight = 1

[[Languages.fr.menu.main]]
name = "Services"
pre = "#"
url = "services"
weight = 2

[[Languages.fr.menu.main]]
name = "Projet"
pre = "#"
url = "portfolio"
weight = 3

[[Languages.fr.menu.main]]
name = "Équipe"
pre = "#"
url = "team"
weight = 4

[[Languages.fr.menu.main]]
name = "Tarifs"
pre = "#"
url = "pricing"
weight = 5

[[Languages.fr.menu.main]]
name = "Blog"
pre = "#"
url = "blog"
weight = 6

[[Languages.fr.menu.main]]
name = "Contact"
pre = "#"
url = "contact"
weight = 7

# [[Languages.fr.menu.main]]
# name = "themefisher"
# pre = ""
# url = "https://themefisher.com/"
# weight = 8

################### English Navigation ########################
[[Languages.en.menu.main]]
name = "About"
pre = "#"
url = "about"
weight = 1

[[Languages.en.menu.main]]
name = "Services"
pre = "#"
url = "services"
weight = 2

[[Languages.en.menu.main]]
name = "Portfolio"
pre = "#"
url = "portfolio"
weight = 3

[[Languages.en.menu.main]]
name = "Team"
pre = "#"
url = "team"
weight = 4

[[Languages.en.menu.main]]
name = "Pricing"
pre = "#"
url = "pricing"
weight = 5

[[Languages.en.menu.main]]
name = "Blog"
pre = "#"
url = "blog"
weight = 6

[[Languages.en.menu.main]]
name = "Contact"
pre = "#"
url = "contact"
weight = 7

# [[Languages.en.menu.main]]
# name = "themefisher"
# pre = ""
# url = "https://themefisher.com/"
# weight = 8


############################# Default Parameters ##########################
[params]
# baseURL = "https://www.lcdigitale.fr"
# contentDir = "content/french"
# languageCode = "fr-fr"
logo = "images/monlogo2.svg"
# Meta data
description = "Développeur web à Blagnac. LCDIGITALE, création de sites web, vitrine, corporate, e-commerce. Conception graphique, logos, plaquettes publicitaires. Marketing Numérique, communication, Seo optimisé."
author = "David Bailly"
# Google Analytics
google_analytics_id = "G-1W0S9VCFWZ" # Your ID
# post share
post_share = true

#base canonique
canonicalUrl = "https://www.lcdigitale.fr"

# preloader
[params.preloader]
enable = false
preloader = "images/logo.png"

# cookies
[params.cookies]
enable = true
expire_days = 15

# google map
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyClIxTji6fpqenBBAzyUs-FLNVJ6Gccz_4"
map_latitude = "43.635087"
map_longitude = "1.39703"  
map_marker = "images/marker.png"

############################# social icons ##########################
# [[params.social]]
# icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
# link = "#"

# [[params.social]]
# icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
# link = "#"

[[params.social]]
icon = "ti-instagram" # themify icon pack : https://themify.me/themify-icons
link = "https://www.instagram.com/lcdigitale/"

[[params.social]]
icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
link = "https://www.linkedin.com/in/davidbailly8"

[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "#"

# [[params.social]]
# icon = "ti-pinterest" # themify icon pack : https://themify.me/themify-icons
# link = "#"



################################ France Language ########################
[Languages.fr]
# baseURL = "fr"
languageName = "Français"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 1
home = "Accueil"
# copyright = "Copyright &copy; 2021 Designed by [Themefisher](https://themefisher.com) & Developed by [Gethugothemes](https://gethugothemes.com)"
copyright = "Copyright &copy; 2021 Conception par [Lc Digitale](https://lcdigitale.fr) & Développé par [David Bailly](https://davidbailly.fr)"



################################ English Language ########################
[Languages.en]
# baseURL = "en"
languageName = "English"
languageCode = "en-us"
contentDir = "content/english"
weight = 2
home = "Home"
copyright = "Copyright &copy; 2020 Designed by [Lc Digitale](https://lcdigitale.fr) & Developed by [David Bailly](https://davidbailly.fr)"

