[build]
  publish = "meghna-hugo/public"
  command = "cd meghna-hugo && hugo --gc --themesDir ../.."
  
[build.environment]
  HUGO_VERSION = "0.79.0"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "/"

  # [submodule "themes/meghna-hugo"]
	# path = themes/meghna-hugo
	# url = https://github.com/themefisher/meghna-hugo.git
